# Appearance
appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: M

# Marketing
marketing:
  seo:
    site_type: Person
    org_name: 'Lehigh University'
    description: 'Disha Kamale is a Ph.D. student at Lehigh University, researching robotics, perception-aware planning, and formal methods. Her work focuses on autonomous systems and control synthesis.'
  verification:
    google: 'HPixiqnukSUkoQ1tQLJtD1nQ_e6FWdqucJvIItidX4c' 

# Site features
features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/dishakamale/robotics'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  search:
    provider: wowchemy